### ISSUE TITLE
Any chance for a CommonLibSSE NG build ?

### ISSUE THREAD

**Issue by Surfingnet** [max-su-2019/CombatPathingRevolution#2]
Latest release doesn't work past 1.6.629. Hope to see 1.6.640 support in future updates.

**Comment by max-su-2019** [comment]
I won't build for AE anymore during personal reason. However, anyone has the permission to port it himself with the source codes.

**Comment by Surfingnet** [comment]
Here I summon the great Doodlezoid and start to wait, for I have not the required skills...

**Comment by alandtse** [comment]
I just realized I'm already building NG. I haven't tested so maybe it works. https://www.nexusmods.com/skyrimspecialedition/mods/87895?tab=description

**Comment by alandtse** [comment]
@max-su-2019 just a heads up, the NG port didn't happen to work due to inlining. I talked to doodlum and given the amount of work, I don't intend to try to port to 1.6. You should probably remove your sticky on your posts as it's directing people to me and I'm getting pissed off people that I'm having to ban.
